name: GGmail Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  cd:
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.release.outputs.RELEASE_BODY }}
    steps:
      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create changes
        shell: bash
        run: touch CHANGES.md

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md

      - name: Set the release body
        id: release
        shell: bash
        run: |
          r=$(cat ${{ steps.git-cliff.outputs.changelog }})
          r="${r//'%'/'%25'}"     # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"   # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"   # Multiline escape sequences for '\r'
          echo "::set-output name=RELEASE_BODY::$r"

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.8
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}

      - name: Upload the binary releases
        uses: svenstaro/upload-release-action@v2
        with:
          file: dist/ggmail-${{ env.RELEASE_VERSION }}.tar.gz
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: "Release v${{ env.RELEASE_VERSION }}"
          tag: ${{ github.ref }}
          body: ${{ steps.release.outputs.RELEASE_BODY }}
